# This old base image is loaded with critical CVEs
FROM node:14-alpine 

MAINTAINER devops@demo.com 

# VULNERABLE: Hardcoded Secret
ENV AWS_SECRET_ACCESS_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY

ADD app.py /app.py 
CMD ["node", "/app.js"]