AWSTemplateFormatVersion: '2010-09-09'
Resources:
  SecureBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "amzn-s3-demo-logging-bucket-${AWS::AccountId}"
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
              
  SecureBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref SecureBucket
      PolicyDocument:
        Statement:
          - Action: s3:*
            Effect: Deny
            Principal: "*"
            Resource: !Sub "arn:aws:s3:::${SecureBucket}/*"
            Condition:
              Bool:
                aws:SecureTransport: "false" # SECURE: Denies non-HTTPS traffic

  SecureDB:
    Type: AWS::RDS::DBCluster
    Properties:
      Engine: aurora-postgresql
      EngineVersion: "15.4"
      EnableIAMDatabaseAuthentication: true # SECURE: Enables IAM Auth
      ManageMasterUserPassword: true
      MasterUsername: clusteradmin