FROM alpine:latest 
# VULNERABLE: Uses 'latest' tag
MAINTAINER devops@demo.com 
# VULNERABLE: MAINTAINER is deprecated

# VULNERABLE: Hardcoded Secret
ENV AWS_SECRET_ACCESS_KEY=AKIAIOSFODNN7EXAMPLE

ADD app.py /app.py # VULNERABLE: ADD used instead of COPY
# VULNERABLE: No HEALTHCHECK defined
# VULNERABLE: No USER defined (runs as root)
CMD ["python", "/app.py"]