name: Prisma Cloud IaC Scan

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development
  workflow_dispatch: # Adds a button to run it manually during the demo

jobs:
  IaC-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Checkov
        run: pip install checkov
        
      - name: Run Prisma Cloud Scan via CLI
        env:
          PRISMA_API_URL: https://api2.prismacloud.io # Verify this matches your specific tenant URL
          BC_API_KEY: ${{ secrets.PC_API_KEY }}
          BC_SOURCE: githubActions
          CKV_SECRETS_SCAN_ENABLE_ALL: "true" # Enable secret scan to scan all type of file
          #CKV_POLICY_METADATA_FILTER: "policy.label=deloitte_demo_policies_iac" # Evaluate a specific group of policies
        run: |
          # --quiet \ Display only failed checks
          # --framework \ # Run on a specific infrastructure#
          # --policy-metadata-filter "policy.label=deloitte_demo_policies_iac" \ # Evaluate a specific group of policies
          checkov -d ${{ github.workspace }}/sca_dockerfile  \
            --repo-id ${{ github.repository }} \
            --branch ${{ github.ref_name }} \
            --use-enforcement-rules \
            -o cli -o sarif \
            --output-bc-ids \
            --output-file-path console,results.sarif
