name: Prisma Cloud IaC Scan

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development
  workflow_dispatch: # Adds a button to run it manually during the demo

jobs:
  kubernetes-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Checkov
        run: pip install checkov
        
      - name: Run Prisma Cloud Scan via CLI
        env:
          PRISMA_API_URL: https://api2.prismacloud.io # Verify this matches your specific tenant URL
          BC_SOURCE: githubActions
        run: |
          checkov -d ${{ github.workspace }}/dockerfile-vulnerable \
            --framework kubernetes \
            --quiet \
            --prisma-api-url $PRISMA_API_URL \
            --bc-api-key ${{ secrets.PC_API_KEY }} \
            --repo-id ${{ github.repository }} \
            --branch ${{ github.ref_name }} \
            --use-enforcement-rules \
            -o cli -o sarif \
            --output-file-path console,results.sarif
